package com.ohuji.cardsNmonsters.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF765B00)
val md_theme_light_onPrimary = Color(0xFFCAC1AA)
val md_theme_light_primaryContainer = Color(0xFF001D35)
val md_theme_light_onPrimaryContainer = Color(0xFFCAC1AA)
val md_theme_light_secondary = Color(0xFF0062A1)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD0E4FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001D35)
val md_theme_light_tertiary = Color(0xFF765B00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDF94)
val md_theme_light_onTertiaryContainer = Color(0xFF251A00)
val md_theme_light_error = Color(0xFFf6f7fc)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFF464544)
val md_theme_light_onBackground = Color(0xFFCAC1AA)
val md_theme_light_surface = Color(0xFF464544)
val md_theme_light_onSurface = Color(0xFF001B3D)
val md_theme_light_surfaceVariant = Color(0xFFf6f7fc)
val md_theme_light_onSurfaceVariant = Color(0xFFFFFFFF)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFECF0FF)
val md_theme_light_inverseSurface = Color(0xFF003062)
val md_theme_light_inversePrimary = Color(0xFFABC7FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF2C5DA7)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFABC7FF)
val md_theme_dark_onPrimary = Color(0xFF002F65)
val md_theme_dark_primaryContainer = Color(0xFF03458E)
val md_theme_dark_onPrimaryContainer = Color(0xFFD7E3FF)
val md_theme_dark_secondary = Color(0xFF9CCAFF)
val md_theme_dark_onSecondary = Color(0xFF003256)
val md_theme_dark_secondaryContainer = Color(0xFF00497A)
val md_theme_dark_onSecondaryContainer = Color(0xFFD0E4FF)
val md_theme_dark_tertiary = Color(0xFFEDC148)
val md_theme_dark_onTertiary = Color(0xFF3E2E00)
val md_theme_dark_tertiaryContainer = Color(0xFF594400)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDF94)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001B3D)
val md_theme_dark_onBackground = Color(0xFFD6E3FF)
val md_theme_dark_surface = Color(0xFF001B3D)
val md_theme_dark_onSurface = Color(0xFFD6E3FF)
val md_theme_dark_surfaceVariant = Color(0xFF44474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_inverseOnSurface = Color(0xFF001B3D)
val md_theme_dark_inverseSurface = Color(0xFFD6E3FF)
val md_theme_dark_inversePrimary = Color(0xFF2C5DA7)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFABC7FF)
val md_theme_dark_outlineVariant = Color(0xFF44474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF142035)


val grey1 = Color(0xFF464544)
val grey2 = Color(0xFF4f4e4d)
val green1 = Color(0xFF3d4b41)
val green2 = Color(0xFF44564a)
val groundgreen = Color(0xFF829676)
val skyblue = Color(0xFF82999f)
val cloudgrey = Color(0xFF898b93)
val light1 = Color(0xFFdbe2db)
val light2 = Color(0xFFf6f7fc)